Move BL with tests to package
ChervotkinaTeam/TodoList pull request #24
Opened 2023-03-16 02:39 UTC by Koloma

2023-03-18 17:37 UTC, elenasheshukova requested changes
SectionForTaskManagerAdapter.swift Кирил не выносил в пакет с БЛ, он в проекте в папке Managers. Давай так же сделаем.

2023-03-18 18:12 UTC, elenasheshukova requested changes

2023-03-18 18:12 UTC, elenasheshukova commented on Framework/TaskManagerPackage/Package.swift
> +			targets: ["TaskManagerPackage"]),
лишняя запятая после targets: ["TaskManagerPackage"])

2023-03-18 18:12 UTC, elenasheshukova commented on Framework/TaskManagerPackage/Package.swift
> +			dependencies: ["TaskManagerPackage"]),
лишняя запятая после dependencies: ["TaskManagerPackage"])

2023-03-19 09:51 UTC, Koloma commented
Переместил SectionForTaskManagerAdapter в TodoListScreen
Удалил лишние запятые. Сразу их не смог удалить, Xcode  глючил и при удалении запятых проект не собирался ;(
теперь все получилось.

2023-03-19 10:38 UTC, elenasheshukova approved these changes

2023-03-19 10:40 UTC, merged