Update README.md
ChervotkinaTeam/TodoList pull request #34
Opened 2023-03-21 16:55 UTC by realersy

Слегка переделал readme файл

2023-03-22 06:18 UTC, elenasheshukova requested changes

2023-03-22 06:18 UTC, elenasheshukova commented on README.md
> +- Создайте новый скипт в проекте в Build Phases и перетащите его до компиляции
Это лишнее. Скрипт уже добавлен в проект, каждому разработчику это не нужно повторять.

Оставь в инструкции что то типа "установите свифтлит через терминал с помощью команды.... , клонируйте репозиторий...., запустите файл TodoList.xcodeproj"

2023-03-22 16:21 UTC, realersy reviewed
Исправления readme file

2023-03-24 08:58 UTC, elenasheshukova approved these changes

2023-03-24 09:00 UTC, merged