Fix ImportantTaskTests
ChervotkinaTeam/TodoList pull request #35
Opened 2023-03-23 12:54 UTC by Koloma

2023-03-23 13:15 UTC, elenasheshukova requested changes

2023-03-23 13:15 UTC, elenasheshukova commented on Framework/TaskManagerPackage/Tests/TaskManagerPackageTests/ImportantTask.swift
лишняя пустая строка

2023-03-23 13:15 UTC, elenasheshukova commented on Framework/TaskManagerPackage/Tests/TaskManagerPackageTests/ImportantTask.swift
> +	func test_createImportantTask_initializationShouldBeValid() {
Мне кажется, это лишний тест.

2023-03-23 13:26 UTC, Koloma commented
Внес правки.

2023-03-24 08:28 UTC, elenasheshukova approved these changes

2023-03-24 08:33 UTC, merged