Add UnitTests for TodoListScene
ChervotkinaTeam/TodoList pull request #44
Opened 2023-03-25 05:22 UTC by Koloma

Не смог придумать как протестировать TodoListViewController

2023-03-26 15:26 UTC, Koloma commented
Доделал тесты для TodoListViewController

2023-03-27 16:42 UTC, elenasheshukova requested changes

2023-03-27 16:42 UTC, elenasheshukova commented on TodoListTests/TodoListScene/TodoListInteractorTests.swift
> +	private let sectionManager = MockSectionForTaskManagerAdapter()
Кажется, что class MockSectionForTaskManagerAdapter нам не нужен, можно сделать так:
`private let sectionManager = SectionForTaskManagerAdapter(taskManager: MockTaskManager())`

2023-03-28 15:09 UTC, Koloma commented
Внес исправления:
private let sectionManager = SectionForTaskManagerAdapter(taskManager: MockTaskManager())

2023-03-29 05:00 UTC, elenasheshukova approved these changes

2023-03-29 05:00 UTC, merged