Remove storyboard
ChervotkinaTeam/TodoList pull request #61
Opened 2023-03-30 14:46 UTC by Koloma

2023-03-30 19:00 UTC, d-karpov approved these changes

2023-03-31 01:36 UTC, elenasheshukova requested changes

2023-03-31 01:36 UTC, elenasheshukova commented on TodoList/Base.lproj/LaunchScreen.storyboard
LaunchScreen.storyboard  нужно оставить

2023-03-31 01:36 UTC, elenasheshukova commented on TodoList/Scenes/LoginScene/LoginViewController.swift
> +	private func buttonLogin(_ sender: Any) { login() }
Ок, визуал настроим в следующем ПР, но 
все view должны быть lazy:
```
private lazy var textFieldLogin = UITextField()
private lazy var textFieldPass = UITextField()
```
не хватает кнопки
`private lazy var buttonLogin = UIButton()`

private func buttonLogin - не нужна, удалить

2023-03-31 02:55 UTC, Koloma commented on TodoList/Base.lproj/LaunchScreen.storyboard
Если мы уходим от storyboard, считаю что и LaunchScreen.storyboard нам не нужен.

2023-03-31 02:56 UTC, Koloma commented
Fix done

2023-03-31 08:30 UTC, elenasheshukova approved these changes

2023-03-31 08:46 UTC, merged